server:
  port: 9090
spring:
  application:
    name: Mapper-Service
  datasource:
    url: jdbc:mysql://localhost:3306/shlok_database
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect